name: publish docker image
on: push
jobs:
  push_docker_image_to_registry:
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses:  docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadate (Tags and labels) for Docker image
        id: meta
        uses: docker/metadate-action@V4
        with:
          
