name: publish docker image
on: push
jobs:
  push_docker_image_to_registry:
    name: Push Docker image to registry
    runs-on: ubuntu-latest
    steps:
      - name: checkout Repo
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses:  docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata (Tags and labels) for Docker image
        id: meta
        uses:  docker/metadata-action@v5
        with:
          images: lilsaint91/class16-create-and-publish-docker-image
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push:  true
          tags: ${{ steps.meat.output.tags }}
          labels: ${{steps.meta.output.labels }}
